// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebLinhKienDienTu.Models;

#nullable disable

namespace WebLinhKienDienTu.Migrations
{
    [DbContext(typeof(QllkContext))]
    [Migration("20251115014700_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebLinhKienDienTu.Models.Chitietgiohang", b =>
                {
                    b.Property<int>("Magh")
                        .HasColumnType("int")
                        .HasColumnName("MAGH");

                    b.Property<string>("Masp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MASP")
                        .IsFixedLength();

                    b.Property<decimal?>("Dongia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DONGIA");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<decimal?>("Thanhtien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29,2)")
                        .HasColumnName("THANHTIEN")
                        .HasComputedColumnSql("([SOLUONG]*[DONGIA])", false);

                    b.HasKey("Magh", "Masp")
                        .HasName("PK_CTGH");

                    b.HasIndex("Masp");

                    b.ToTable("CHITIETGIOHANG", (string)null);
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Chitiethoadon", b =>
                {
                    b.Property<string>("Mahd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MAHD")
                        .IsFixedLength();

                    b.Property<string>("Masp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MASP")
                        .IsFixedLength();

                    b.Property<decimal?>("Dongia")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("DONGIA");

                    b.Property<string>("Makho")
                        .IsRequired()
                        .HasColumnType("char(20)")
                        .HasColumnName("MAKHO");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<decimal?>("Thanhtien")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("THANHTIEN");

                    b.HasKey("Mahd", "Masp")
                        .HasName("PK_CTHD");

                    b.HasIndex("Makho");

                    b.HasIndex("Masp");

                    b.ToTable("CHITIETHOADON", (string)null);
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Giohang", b =>
                {
                    b.Property<int>("Magh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAGH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Magh"), 1L, 1);

                    b.Property<string>("Mahd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MAHD")
                        .IsFixedLength();

                    b.Property<string>("Makh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MAKH")
                        .IsFixedLength();

                    b.Property<string>("Masp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MASP")
                        .IsFixedLength();

                    b.Property<int?>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.HasKey("Magh")
                        .HasName("PK__GIOHANG__603F38A3C0DE190B");

                    b.HasIndex("Mahd");

                    b.HasIndex("Makh");

                    b.HasIndex("Masp");

                    b.ToTable("GIOHANG", (string)null);
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Hoadon", b =>
                {
                    b.Property<string>("Mahd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MAHD")
                        .IsFixedLength();

                    b.Property<string>("Makh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MAKH")
                        .IsFixedLength();

                    b.Property<string>("Manv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MANV")
                        .IsFixedLength();

                    b.Property<DateTime?>("Ngaylap")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYLAP");

                    b.Property<decimal?>("Tongtien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TONGTIEN");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mahd")
                        .HasName("PK_HD");

                    b.HasIndex("Makh");

                    b.HasIndex("Manv");

                    b.ToTable("HOADON", (string)null);
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Khachhang", b =>
                {
                    b.Property<string>("Makh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MAKH")
                        .IsFixedLength();

                    b.Property<string>("Diachi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime?>("Ngaytao")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTAO");

                    b.Property<string>("Sdt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tenkh")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("TENKH");

                    b.HasKey("Makh")
                        .HasName("PK_KH");

                    b.HasIndex("Email");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Khohang", b =>
                {
                    b.Property<string>("Makho")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MAKHO")
                        .IsFixedLength();

                    b.Property<string>("Diachikho")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DIACHIKHO");

                    b.Property<string>("Manv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MANV")
                        .IsFixedLength();

                    b.Property<string>("Soluongloaihang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SOLUONGLOAIHANG");

                    b.Property<string>("Tenkho")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TENKHO");

                    b.HasKey("Makho")
                        .HasName("PK__KHOHANG__CA1EB690DBCC293B");

                    b.ToTable("KHOHANG", (string)null);
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.KhoSanpham", b =>
                {
                    b.Property<string>("Makho")
                        .HasColumnType("char(20)")
                        .HasColumnName("MAKHO");

                    b.Property<string>("Masp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MASP")
                        .IsFixedLength();

                    b.Property<DateTime>("Ngaynhap")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYNHAP");

                    b.Property<int?>("Soluongnhap")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONGNHAP");

                    b.HasKey("Makho", "Masp", "Ngaynhap")
                        .HasName("PK_K_SP");

                    b.HasIndex("Masp");

                    b.ToTable("KHO_SANPHAM", (string)null);
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Lichsuhoatdong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Chitiet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CHITIET");

                    b.Property<string>("Doituong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DOITUONG");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Hoatdong")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("HOATDONG");

                    b.Property<DateTime?>("Thoigian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("THOIGIAN")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__LICHSUHO__3214EC2713995A09");

                    b.HasIndex("Email");

                    b.ToTable("LICHSUHOATDONG", (string)null);
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Lichsumuahang", b =>
                {
                    b.Property<string>("Malsmh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MALSMH")
                        .IsFixedLength();

                    b.Property<string>("Mahd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MAHD")
                        .IsFixedLength();

                    b.Property<string>("Makh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MAKH")
                        .IsFixedLength();

                    b.Property<DateTime?>("Ngaymua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYMUA")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("Tongtien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TONGTIEN");

                    b.Property<string>("Trangthai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Hoàn tất")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Malsmh")
                        .HasName("PK_LSMH");

                    b.HasIndex("Mahd");

                    b.HasIndex("Makh");

                    b.ToTable("LICHSUMUAHANG", (string)null);
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Loaisanpham", b =>
                {
                    b.Property<string>("Maloai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MALOAI")
                        .IsFixedLength();

                    b.Property<string>("Mota")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tenloai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENLOAI");

                    b.HasKey("Maloai")
                        .HasName("PK_LSP");

                    b.ToTable("LOAISANPHAM", (string)null);
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Nhanvien", b =>
                {
                    b.Property<string>("Manv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MANV")
                        .IsFixedLength();

                    b.Property<string>("Chuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CHUC");

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Gioitinh")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("GIOITINH");

                    b.Property<decimal?>("Luong")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("LUONG");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYSINH");

                    b.Property<int?>("Sdt")
                        .HasColumnType("int")
                        .HasColumnName("SDT");

                    b.Property<string>("Tennv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TENNV");

                    b.HasKey("Manv")
                        .HasName("PK_NV");

                    b.HasIndex("Email");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Sanpham", b =>
                {
                    b.Property<string>("Masp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MASP")
                        .IsFixedLength();

                    b.Property<decimal?>("Dongia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DONGIA");

                    b.Property<string>("Dvt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DVT");

                    b.Property<string>("Hinhanh")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("char(200)")
                        .HasColumnName("HINHANH")
                        .IsFixedLength();

                    b.Property<string>("Maloai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MALOAI")
                        .IsFixedLength();

                    b.Property<string>("Mota")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MOTA");

                    b.Property<int?>("Soluongton")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONGTON");

                    b.Property<string>("Tensp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENSP");

                    b.HasKey("Masp")
                        .HasName("PK_SP");

                    b.HasIndex("Maloai");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Taikhoan", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Pass")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("PASS")
                        .IsFixedLength();

                    b.Property<string>("Quyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("QUYEN");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Email")
                        .HasName("PK_TK");

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Thanhtoan", b =>
                {
                    b.Property<string>("Matt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MATT")
                        .IsFixedLength();

                    b.Property<string>("Mahd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("MAHD")
                        .IsFixedLength();

                    b.Property<DateTime?>("Ngaytt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Phuongthuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PHUONGTHUC");

                    b.Property<decimal?>("Tongtien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TONGTIEN");

                    b.Property<string>("Trangthai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Đã thanh toán")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Matt")
                        .HasName("PK_TT");

                    b.HasIndex("Mahd");

                    b.ToTable("THANHTOAN", (string)null);
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Chitietgiohang", b =>
                {
                    b.HasOne("WebLinhKienDienTu.Models.Giohang", "MaghNavigation")
                        .WithMany("Chitietgiohangs")
                        .HasForeignKey("Magh")
                        .IsRequired()
                        .HasConstraintName("FK_CTGH_GH");

                    b.HasOne("WebLinhKienDienTu.Models.Sanpham", "MaspNavigation")
                        .WithMany("Chitietgiohangs")
                        .HasForeignKey("Masp")
                        .IsRequired()
                        .HasConstraintName("FK_CTGH_SP");

                    b.Navigation("MaghNavigation");

                    b.Navigation("MaspNavigation");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Chitiethoadon", b =>
                {
                    b.HasOne("WebLinhKienDienTu.Models.Hoadon", "MahdNavigation")
                        .WithMany("Chitiethoadons")
                        .HasForeignKey("Mahd")
                        .IsRequired()
                        .HasConstraintName("FK_CTHD_HD");

                    b.HasOne("WebLinhKienDienTu.Models.Khohang", "SttNavigation")
                        .WithMany("Chitiethoadons")
                        .HasForeignKey("Makho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CTHD_K");

                    b.HasOne("WebLinhKienDienTu.Models.Sanpham", "MaspNavigation")
                        .WithMany("Chitiethoadons")
                        .HasForeignKey("Masp")
                        .IsRequired()
                        .HasConstraintName("FK_CTHD_SP");

                    b.Navigation("MahdNavigation");

                    b.Navigation("MaspNavigation");

                    b.Navigation("SttNavigation");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Giohang", b =>
                {
                    b.HasOne("WebLinhKienDienTu.Models.Hoadon", "MahdNavigation")
                        .WithMany("Giohangs")
                        .HasForeignKey("Mahd")
                        .HasConstraintName("FK_GH_HD");

                    b.HasOne("WebLinhKienDienTu.Models.Khachhang", "MakhNavigation")
                        .WithMany("Giohangs")
                        .HasForeignKey("Makh")
                        .IsRequired()
                        .HasConstraintName("FK_GH_KH");

                    b.HasOne("WebLinhKienDienTu.Models.Sanpham", "MaspNavigation")
                        .WithMany("Giohangs")
                        .HasForeignKey("Masp")
                        .IsRequired()
                        .HasConstraintName("FK_GH_SP");

                    b.Navigation("MahdNavigation");

                    b.Navigation("MakhNavigation");

                    b.Navigation("MaspNavigation");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Hoadon", b =>
                {
                    b.HasOne("WebLinhKienDienTu.Models.Khachhang", "MakhNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Makh")
                        .HasConstraintName("FK_HD_KH");

                    b.HasOne("WebLinhKienDienTu.Models.Nhanvien", "ManvNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_H_NV");

                    b.Navigation("MakhNavigation");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Khachhang", b =>
                {
                    b.HasOne("WebLinhKienDienTu.Models.Taikhoan", "EmailNavigation")
                        .WithMany("Khachhangs")
                        .HasForeignKey("Email")
                        .HasConstraintName("FK_KH_TK");

                    b.Navigation("EmailNavigation");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.KhoSanpham", b =>
                {
                    b.HasOne("WebLinhKienDienTu.Models.Khohang", "SttNavigation")
                        .WithMany("KhoSanphams")
                        .HasForeignKey("Makho")
                        .IsRequired()
                        .HasConstraintName("FK_KSP_KHO");

                    b.HasOne("WebLinhKienDienTu.Models.Sanpham", "MaspNavigation")
                        .WithMany("KhoSanphams")
                        .HasForeignKey("Masp")
                        .IsRequired()
                        .HasConstraintName("FK_KSP_SANPHAM");

                    b.Navigation("MaspNavigation");

                    b.Navigation("SttNavigation");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Lichsuhoatdong", b =>
                {
                    b.HasOne("WebLinhKienDienTu.Models.Taikhoan", "EmailNavigation")
                        .WithMany("Lichsuhoatdongs")
                        .HasForeignKey("Email")
                        .IsRequired()
                        .HasConstraintName("FK_LICHSUHOATDONG_TAIKHOAN");

                    b.Navigation("EmailNavigation");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Lichsumuahang", b =>
                {
                    b.HasOne("WebLinhKienDienTu.Models.Hoadon", "MahdNavigation")
                        .WithMany("Lichsumuahangs")
                        .HasForeignKey("Mahd")
                        .IsRequired()
                        .HasConstraintName("FK_LSMH_HD");

                    b.HasOne("WebLinhKienDienTu.Models.Khachhang", "MakhNavigation")
                        .WithMany("Lichsumuahangs")
                        .HasForeignKey("Makh")
                        .IsRequired()
                        .HasConstraintName("FK_LSMH_KH");

                    b.Navigation("MahdNavigation");

                    b.Navigation("MakhNavigation");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Nhanvien", b =>
                {
                    b.HasOne("WebLinhKienDienTu.Models.Taikhoan", "EmailNavigation")
                        .WithMany("Nhanviens")
                        .HasForeignKey("Email")
                        .HasConstraintName("FK_NV_TK");

                    b.Navigation("EmailNavigation");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Sanpham", b =>
                {
                    b.HasOne("WebLinhKienDienTu.Models.Loaisanpham", "MaloaiNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("Maloai")
                        .HasConstraintName("FK_SP_LSP");

                    b.Navigation("MaloaiNavigation");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Thanhtoan", b =>
                {
                    b.HasOne("WebLinhKienDienTu.Models.Hoadon", "MahdNavigation")
                        .WithMany("Thanhtoans")
                        .HasForeignKey("Mahd")
                        .IsRequired()
                        .HasConstraintName("FK_TT_HD");

                    b.Navigation("MahdNavigation");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Giohang", b =>
                {
                    b.Navigation("Chitietgiohangs");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Hoadon", b =>
                {
                    b.Navigation("Chitiethoadons");

                    b.Navigation("Giohangs");

                    b.Navigation("Lichsumuahangs");

                    b.Navigation("Thanhtoans");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Khachhang", b =>
                {
                    b.Navigation("Giohangs");

                    b.Navigation("Hoadons");

                    b.Navigation("Lichsumuahangs");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Khohang", b =>
                {
                    b.Navigation("Chitiethoadons");

                    b.Navigation("KhoSanphams");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Loaisanpham", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Nhanvien", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Sanpham", b =>
                {
                    b.Navigation("Chitietgiohangs");

                    b.Navigation("Chitiethoadons");

                    b.Navigation("Giohangs");

                    b.Navigation("KhoSanphams");
                });

            modelBuilder.Entity("WebLinhKienDienTu.Models.Taikhoan", b =>
                {
                    b.Navigation("Khachhangs");

                    b.Navigation("Lichsuhoatdongs");

                    b.Navigation("Nhanviens");
                });
#pragma warning restore 612, 618
        }
    }
}
