GO
CREATE DATABASE QLLK
GO
USE QLLK
GO
CREATE TABLE TAIKHOAN(EMAIL NVARCHAR(100) NOT NULL,
					PASS CHAR(50),
					QUYEN NVARCHAR(50),
					TRANGTHAI NVARCHAR(20))
GO
CREATE TABLE KHACHHANG(MAKH CHAR(20) NOT NULL,
						TENKH NVARCHAR(70),
						SDT VARCHAR(10),
						EMAIL NVARCHAR(100),
						DIACHI NVARCHAR(100),
						NGAYTAO DATETIME
						)
GO
CREATE TABLE LOAISANPHAM(MALOAI CHAR(20) NOT NULL,
						TENLOAI NVARCHAR(100),
						MOTA NVARCHAR(100))
GO
CREATE TABLE SANPHAM(MASP CHAR(20) NOT NULL,
						TENSP NVARCHAR(100),
						DONGIA DECIMAL(18,2),
						DVT NVARCHAR(50),
						SOLUONGTON INT,
						MALOAI CHAR(20))
GO
CREATE TABLE KHOHANG(MAKHO CHAR(20) NOT NULL,
						TENKHO NVARCHAR(100),
						DIACHIKHO NVARCHAR(200))
GO
CREATE TABLE KHO_SANPHAM(MAKHO CHAR(20) NOT NULL,
							MASP CHAR(20) NOT NULL,
							NGAYNHAP DATETIME NOT NULL,
							SOLUONGNHAP INT)
GO
CREATE TABLE HOADON(MAHD CHAR(20) NOT NULL,
					NGAYLAP DATETIME,
					TONGTIEN DECIMAL(18,2),
					MAKH CHAR(20),
					MATK CHAR(20),
					MANV CHAR(20))
GO
CREATE TABLE CHITIETHOADON(MAHD CHAR(20) NOT NULL,
							MASP CHAR(20) NOT NULL,
							MAKHO CHAR(20),
							SOLUONG INT,
							DONGIA DECIMAL,
							THANHTIEN DECIMAL)
GO
CREATE TABLE NHANVIEN(MANV CHAR(20) NOT NULL,
						TENNV NVARCHAR(30) NOT NULL,
						GIOITINH NVARCHAR(5),
						NGAYSINH DATE,
						CHUC NVARCHAR(50),
						LUONG DECIMAL,
						DIACHI NVARCHAR(50),
						SDT INT,
						EMAIL NVARCHAR(100))

-------------------RÀNG BUỘC KHÓA CHÍNH-------------------
GO
ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NV PRIMARY KEY(MANV)

GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT PK_TK PRIMARY KEY(EMAIL)

GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT PK_KH PRIMARY KEY(MAKH)

GO
ALTER TABLE LOAISANPHAM
ADD CONSTRAINT PK_LSP PRIMARY KEY(MALOAI)

GO
ALTER TABLE SANPHAM
ADD CONSTRAINT PK_SP PRIMARY KEY(MASP)

GO
ALTER TABLE KHOHANG
ADD CONSTRAINT PK_KHO PRIMARY KEY(MAKHO)

GO
ALTER TABLE KHO_SANPHAM
ADD CONSTRAINT PK_K_SP PRIMARY KEY(MAKHO,MASP,NGAYNHAP)

GO
ALTER TABLE HOADON
ADD CONSTRAINT PK_HD PRIMARY KEY(MAHD)

GO
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT PK_CTHD PRIMARY KEY(MAHD,MASP)

-------------------RÀNG BUỘC KHÓA NGOẠI-------------------
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KH_TK FOREIGN KEY (EMAIL)
REFERENCES TAIKHOAN(EMAIL);

-- 2. Nhân viên ↔ Tài khoản (1–1)
GO
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_TK FOREIGN KEY (EMAIL)
REFERENCES TAIKHOAN(EMAIL);

-- 3. Hóa đơn ↔ Khách hàng (1–n)
GO
ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_KH FOREIGN KEY (MaKH)
REFERENCES KHACHHANG(MaKH);

-- 4. Hóa đơn ↔ Nhân viên (1–n)
GO
ALTER TABLE HOADON
ADD CONSTRAINT FK_H_NV FOREIGN KEY (MaNV)
REFERENCES NHANVIEN(MaNV);

-- 5. Chi tiết hóa đơn ↔ Hóa đơn
GO
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY (MaHD)
REFERENCES HOADON(MaHD);

-- 6. Chi tiết hóa đơn ↔ Sản phẩm
GO
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CTHD_SP FOREIGN KEY (MaSP)
REFERENCES SANPHAM(MaSP);

GO
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CTHD_K FOREIGN KEY (MAKHO)
REFERENCES KHOHANG(MAKHO);

-- 7. Sản phẩm ↔ Loại sản phẩm (1–n)
GO
ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SP_LSP FOREIGN KEY (MaLoai)
REFERENCES LOAISANPHAM(MaLoai);

-- 8. Kho_SanPham ↔ Kho
GO
ALTER TABLE KHO_SANPHAM
ADD CONSTRAINT FK_KSP_KHO FOREIGN KEY (MAKHO)
REFERENCES KHOHANG(MAKHO);

-- 9. Kho_SanPham ↔ Sản phẩm
GO
ALTER TABLE KHO_SANPHAM
ADD CONSTRAINT FK_KSP_SANPHAM FOREIGN KEY (MaSP)
REFERENCES SANPHAM(MaSP);

USE QLLK
GO

-------------------BẢNG GIỎ HÀNG-------------------
CREATE TABLE GIOHANG (
    MAGH CHAR(20) NOT NULL,
    MAKH CHAR(20) NOT NULL,
    NGAYTAO DATETIME DEFAULT GETDATE(),
    TRANGTHAI NVARCHAR(30) DEFAULT N'Chưa thanh toán',
    MAHD CHAR(20) NULL
)
GO
ALTER TABLE GIOHANG
ADD CONSTRAINT PK_GH PRIMARY KEY(MAGH)

-- Liên kết giỏ hàng với khách hàng
ALTER TABLE GIOHANG
ADD CONSTRAINT FK_GH_KH FOREIGN KEY (MAKH)
REFERENCES KHACHHANG(MAKH)

-- Liên kết giỏ hàng với hóa đơn
ALTER TABLE GIOHANG
ADD CONSTRAINT FK_GH_HD FOREIGN KEY (MAHD)
REFERENCES HOADON(MAHD)
GO


-------------------BẢNG CHI TIẾT GIỎ HÀNG-------------------
CREATE TABLE CHITIETGIOHANG (
    MAGH CHAR(20) NOT NULL,
    MASP CHAR(20) NOT NULL,
    SOLUONG INT CHECK(SOLUONG > 0),
    DONGIA DECIMAL(18,2),
    THANHTIEN AS (SOLUONG * DONGIA)
)
GO
ALTER TABLE CHITIETGIOHANG
ADD CONSTRAINT PK_CTGH PRIMARY KEY(MAGH, MASP)

ALTER TABLE CHITIETGIOHANG
ADD CONSTRAINT FK_CTGH_GH FOREIGN KEY (MAGH)
REFERENCES GIOHANG(MAGH)

ALTER TABLE CHITIETGIOHANG
ADD CONSTRAINT FK_CTGH_SP FOREIGN KEY (MASP)
REFERENCES SANPHAM(MASP)
GO


-------------------BẢNG THANH TOÁN-------------------
CREATE TABLE THANHTOAN (
    MATT CHAR(20) NOT NULL,
    MAHD CHAR(20) NOT NULL,
    PHUONGTHUC NVARCHAR(50),
    NGAYTT DATETIME DEFAULT GETDATE(),
    TONGTIEN DECIMAL(18,2),
    TRANGTHAI NVARCHAR(30) DEFAULT N'Đã thanh toán'
)
GO
ALTER TABLE THANHTOAN
ADD CONSTRAINT PK_TT PRIMARY KEY(MATT)

ALTER TABLE THANHTOAN
ADD CONSTRAINT FK_TT_HD FOREIGN KEY (MAHD)
REFERENCES HOADON(MAHD)
GO


-------------------BẢNG LỊCH SỬ ĐĂNG NHẬP-------------------
CREATE TABLE LICHSUDANGNHAP (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    EMAIL NVARCHAR(100) NOT NULL,
    THOIGIAN DATETIME DEFAULT GETDATE(),
    DIACHIIP VARCHAR(50),
    THIETBI NVARCHAR(100),
    TRANGTHAI NVARCHAR(50)
)
GO
ALTER TABLE LICHSUDANGNHAP
ADD CONSTRAINT FK_LSDN_TK FOREIGN KEY (EMAIL)
REFERENCES TAIKHOAN(EMAIL)
GO


-------------------BẢNG LỊCH SỬ MUA HÀNG-------------------
CREATE TABLE LICHSUMUAHANG (
    MALSMH CHAR(20) NOT NULL,
    MAKH CHAR(20) NOT NULL,
    MAHD CHAR(20) NOT NULL,
    NGAYMUA DATETIME DEFAULT GETDATE(),
    TONGTIEN DECIMAL(18,2),
    TRANGTHAI NVARCHAR(30) DEFAULT N'Hoàn tất'
)
GO
ALTER TABLE LICHSUMUAHANG
ADD CONSTRAINT PK_LSMH PRIMARY KEY(MALSMH)

ALTER TABLE LICHSUMUAHANG
ADD CONSTRAINT FK_LSMH_KH FOREIGN KEY (MAKH)
REFERENCES KHACHHANG(MAKH)

ALTER TABLE LICHSUMUAHANG
ADD CONSTRAINT FK_LSMH_HD FOREIGN KEY (MAHD)
REFERENCES HOADON(MAHD)
GO
